/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.pegawai;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author deric
 */
public class GuiBahan extends javax.swing.JFrame {

    String id;
    boolean vsimpan;
    /**
     * Creates new form GuiBahan
     */
    public GuiBahan() {
        initComponents();
        refresh();
    }
 public String autoid(){
try {
 Integer Count;
        Connection conn =(Connection)app.pegawai.Database.koneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet sql = stm.executeQuery("select id from bahan order by id DESC");
        if (!sql.next()){
         Count = 1;
        }else{
         Count = sql.getInt("id")+1;
        }
        id = Integer.toString(Count);
    }
    catch (SQLException | HeadlessException e) {
    }
     return id;
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private void GetData(){ // menampilkan data dari database
    try {
        Connection conn =(Connection)app.pegawai.Database.koneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet sql = stm.executeQuery("select * from bahan");
        data.setModel(DbUtils.resultSetToTableModel(sql));

    }
    catch (SQLException | HeadlessException e) {
    }
}
    public void refresh(){
        txtbahan.setText("");
        
        txtbahan.setEnabled(false);
        
        btnin.setEnabled(true);
        btntam.setEnabled(false);
        btnref.setEnabled(false);
        btnedt.setEnabled(false);
        btnhap.setEnabled(false);
        GetData();
        id=autoid();
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtbahan = new javax.swing.JTextField();
        btnkel = new javax.swing.JButton();
        btnin = new javax.swing.JButton();
        btntam = new javax.swing.JButton();
        btnref = new javax.swing.JButton();
        btnedt = new javax.swing.JButton();
        btnhap = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BAHAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nama Bahan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel1.add(txtbahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 140, 30));

        btnkel.setText("Keluar");
        btnkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkelActionPerformed(evt);
            }
        });
        jPanel1.add(btnkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        btnin.setText("input");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });
        jPanel1.add(btnin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        btntam.setText("Tambah");
        btntam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntamActionPerformed(evt);
            }
        });
        jPanel1.add(btntam, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        btnref.setText("Refresh");
        btnref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefActionPerformed(evt);
            }
        });
        jPanel1.add(btnref, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        btnedt.setText("Edit");
        btnedt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedtActionPerformed(evt);
            }
        });
        jPanel1.add(btnedt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        btnhap.setText("Hapus");
        btnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 140));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 150));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkelActionPerformed
int jawab = JOptionPane.showOptionDialog(this, 
                        "Ingin Keluar?", 
                        "Keluar", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
            GuiMain main = new GuiMain();
            main.Screenmenu();
            
            setVisible(false);
            

        
        }            // TODO add your handling code here:
    }//GEN-LAST:event_btnkelActionPerformed

    private void btnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapActionPerformed
   int jawab = JOptionPane.showOptionDialog(this, 
                        "Ingin Menghapus Data??", 
                        "Hapus Data", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
            
         
        try{
            String sql = "delete from bahan where id = '"+ id +"'";
            java.sql.Connection conn = (java.sql.Connection)app.pegawai.Database.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, " Data Telah Terhapus");
            }catch (SQLException | HeadlessException e){
            }
        refresh();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapActionPerformed

    private void btnrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefActionPerformed
refresh();
// TODO add your handling code here:
    }//GEN-LAST:event_btnrefActionPerformed

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        vsimpan=true;
        txtbahan.setEnabled(true);
        
    btnin.setEnabled(false);
    btntam.setEnabled(true);
    btnedt.setEnabled(false);
    btnhap.setEnabled(false);
    btnref.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btninActionPerformed

    private void btnedtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedtActionPerformed
        vsimpan=false;
        txtbahan.setEnabled(true);
        
    btnin.setEnabled(false);
    btntam.setEnabled(true);
    btnedt.setEnabled(false);
    btnhap.setEnabled(false);
    btnref.setEnabled(true);         // TODO add your handling code here:
    }//GEN-LAST:event_btnedtActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
try{
        int row = data.getSelectedRow();
        String table_klik = (data.getModel().getValueAt(row, 0).toString());
          java.sql.Connection conn = (java.sql.Connection)app.pegawai.Database.koneksiDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("Select * from bahan where id = '"+table_klik+"'");
     if(sql.next()){
         id = sql.getString("id");
         
         String bahan = sql.getString("bahan");
         txtbahan.setText(bahan);

     }
     }catch (Exception e){}
      btnin.setEnabled(false);
      btntam.setEnabled(false);
      btnref.setEnabled(true);
      btnedt.setEnabled(true);
      btnhap.setEnabled(true);    
    }//GEN-LAST:event_dataMouseClicked

    private void btntamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntamActionPerformed
        furniture us = new bahan();
        String bahan,cari;
        
        cari = "Select * from bahan where bahan = '" + txtbahan.getText() + "' ";

            Database db = new Database();
       if ((txtbahan.getText().length()==0) ){
           JOptionPane.showMessageDialog(null, " Data Tidak Lengkap!!!");
  }else{

               
               bahan = txtbahan.getText();
               us.setBahan(bahan);
           
           if (vsimpan == true){
     try
     {     
       if (db.CariData(cari) == true) {
           JOptionPane.showMessageDialog(null, " Data Sudah Ada!!!");
       }else{
        String sql = "insert into bahan Values ('"+id+ "', '" + us.getBahan() + "')";
        java.sql.Connection conn = (java.sql.Connection)app.pegawai.Database.koneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
        refresh();
       }
    } catch (SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);
    }
     
    }else{
         try{
                    if (db.CariData(cari) == true) {
           JOptionPane.showMessageDialog(null, " Data Sudah Ada!!!");
       }else{
    
                   
        String sql = "update bahan set bahan= '" + us.getBahan() +"' where id='" + id + "'";
        java.sql.Connection conn = (java.sql.Connection)app.pegawai.Database.koneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
          refresh();
                    }
            }catch (SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);
                    }
       
               }        
   
       }
    }//GEN-LAST:event_btntamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void ScreenBahan() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiBahan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
    UIManager.setLookAndFeel( new FlatDarkLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiBahan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedt;
    private javax.swing.JButton btnhap;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnkel;
    private javax.swing.JButton btnref;
    private javax.swing.JButton btntam;
    private javax.swing.JTable data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbahan;
    // End of variables declaration//GEN-END:variables
}
