/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.pegawai;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author deric
 */
public class GuiFurniture extends javax.swing.JFrame {
 String id;
 boolean vsimpan;
    /**
     * Creates new form GuiFurniture
     */
    public GuiFurniture() {
        initComponents();
        refresh();
    }

    public String autoid(){
try {
 Integer Count;
        Connection conn =(Connection)app.pegawai.Database.koneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet sql = stm.executeQuery("select id from furnitur order by id DESC");
        if (!sql.next()){
         Count = 1;
        }else{
         Count = sql.getInt("id")+1;
        }
        id = Integer.toString(Count);
    }
    catch (SQLException | HeadlessException e) {
    }
     return id;
 }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void GetData(){ // menampilkan data dari database
    try {
        Connection conn =(Connection)app.pegawai.Database.koneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet sql = stm.executeQuery("select * from furnitur");
        data.setModel(DbUtils.resultSetToTableModel(sql));

    }
    catch (SQLException | HeadlessException e) {
    }
}
    
    public void refresh(){
        txtnama.setText("");
        txtjum.setText("");
        txthar.setText("");

        isiJen();
        
        isiBah();

        txtnama.setEnabled(false);
        txtjum.setEnabled(false);
        txthar.setEnabled(false);
        cmbjen.setEnabled(false);
        cmbbah.setEnabled(false);
        
        btnin.setEnabled(true);
        btntam.setEnabled(false);
        btnref.setEnabled(false);
        btnedt.setEnabled(false);
        btnhap.setEnabled(false);
        GetData();
        id=autoid();
    }
    public void isiJen(){
         String tes;
     
    
     tes = "Select jenis from jenis";
     try{
         cmbjen.removeAllItems();
         cmbjen.addItem("");
         
         Connection conn =(Connection)app.pegawai.Database.koneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet sql = stm.executeQuery(tes);
       while(sql.next()){
        cmbjen.addItem(sql.getString(1));
       }

    }
    catch (SQLException | HeadlessException e) {
    
     }
    }
    
    public void isiBah(){
          String tes;
     
    
     tes = "Select bahan from bahan";
     try{
         cmbbah.removeAllItems();
         cmbbah.addItem("");
         
         Connection conn =(Connection)app.pegawai.Database.koneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet sql = stm.executeQuery(tes);
       while(sql.next()){
        cmbbah.addItem(sql.getString(1));
       }

    }
    catch (SQLException | HeadlessException e) {
    
     }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtjum = new javax.swing.JTextField();
        txthar = new javax.swing.JTextField();
        btnkel = new javax.swing.JButton();
        btnin = new javax.swing.JButton();
        btntam = new javax.swing.JButton();
        btnref = new javax.swing.JButton();
        btnedt = new javax.swing.JButton();
        btnhap = new javax.swing.JButton();
        cmbbah = new javax.swing.JComboBox<>();
        cmbjen = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("FURNITURE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 11, -1, -1));

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("Jenis");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("Bahan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setText("Jumlah");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 61, -1, -1));

        jLabel6.setText("Harga");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 99, -1, -1));
        jPanel1.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 124, -1));
        jPanel1.add(txtjum, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 58, 124, -1));
        jPanel1.add(txthar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 124, -1));

        btnkel.setText("Keluar");
        btnkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkelActionPerformed(evt);
            }
        });
        jPanel1.add(btnkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        btnin.setText("Input");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });
        jPanel1.add(btnin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btntam.setText("Tambah");
        btntam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntamActionPerformed(evt);
            }
        });
        jPanel1.add(btntam, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        btnref.setText("Refresh");
        btnref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefActionPerformed(evt);
            }
        });
        jPanel1.add(btnref, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        btnedt.setText("Edit");
        btnedt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedtActionPerformed(evt);
            }
        });
        jPanel1.add(btnedt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        btnhap.setText("Hapus");
        btnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        cmbbah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, -1));

        cmbjen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbjen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 200));

        data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 510, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkelActionPerformed
int jawab = JOptionPane.showOptionDialog(this, 
                        "Ingin Keluar?", 
                        "Keluar", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
            GuiMain main = new GuiMain();
            main.Screenmenu();
            
            setVisible(false);
            

        
        }            // TODO add your handling code here:
    }//GEN-LAST:event_btnkelActionPerformed

    private void btnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapActionPerformed
   int jawab = JOptionPane.showOptionDialog(this, 
                        "Ingin Menghapus Data??", 
                        "Hapus Data", 
                        JOptionPane.YES_NO_OPTION, 
                        JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
            
         
        try{
            String sql = "delete from furnitur where id = '"+ id +"'";
            java.sql.Connection conn = (java.sql.Connection)app.pegawai.Database.koneksiDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, " Data Telah Terhapus");
            }catch (SQLException | HeadlessException e){
            }
        refresh();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapActionPerformed

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        vsimpan = true;
        txtnama.setEnabled(true);
        txtjum.setEnabled(true);
        txthar.setEnabled(true);
        cmbjen.setEnabled(true);
        cmbbah.setEnabled(true);
        
        btnin.setEnabled(false);
        btntam.setEnabled(true);
        btnref.setEnabled(true);
        btnedt.setEnabled(false);
        btnhap.setEnabled(false);
    }//GEN-LAST:event_btninActionPerformed

    private void btnrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefActionPerformed
        refresh();   
    }//GEN-LAST:event_btnrefActionPerformed

    private void btnedtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedtActionPerformed
        vsimpan = false;
        txtnama.setEnabled(true);
        txtjum.setEnabled(true);
        txthar.setEnabled(true);
        cmbjen.setEnabled(true);
        cmbbah.setEnabled(true);
        
        btnin.setEnabled(false);
        btntam.setEnabled(true);
        btnref.setEnabled(true);
        btnedt.setEnabled(false);
        btnhap.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnedtActionPerformed

    private void btntamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntamActionPerformed
 furniture us = new furniture();
        String nama,jenis,bahan,cari;
        int jumlah;
        double harga;
        
        cari = "Select * from furnitur where nama = '" + txtnama.getText() + "' AND jenis = '" + cmbjen.getSelectedItem() + "' AND bahan = '" +cmbbah.getSelectedItem() + "' ";

            Database db = new Database();
       if ((txtnama.getText().length()==0) || (cmbjen.getSelectedItem()=="")|| (cmbbah.getSelectedItem()=="") || (txtjum.getText().length()==0) || (txthar.getText().length()==0) ){
           JOptionPane.showMessageDialog(null, " Data Tidak Lengkap!!!");
  }else{
               nama = txtnama.getText();
               us.setNama(nama);
               jenis =(String) cmbjen.getSelectedItem();
               us.setJenis(jenis);
               bahan =(String) cmbbah.getSelectedItem();
               us.setBahan(bahan);
               jumlah = Integer.parseInt (txtjum.getText());
               us.setJumlah(jumlah);
               harga = Double.parseDouble(txthar.getText());
               us.setHarga(harga);
               
           if (vsimpan == true){
     try
     {     
       if (db.CariData(cari) == true) {
           JOptionPane.showMessageDialog(null, " Data Sudah Ada!!!");
       }else{
        String sql = "insert into furnitur Values ('"+id+ "', '" + us.getNama() + "', '" + us.getJenis() + "', '" + us.getBahan() + "', '" + us.getJumlah() + "', '" + us.getHarga() + "')";
        java.sql.Connection conn = (java.sql.Connection)app.pegawai.Database.koneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
        refresh();
       }
    } catch (SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);
    }
     
    }else{
         try{
                    if (db.CariData(cari) == true) {
           JOptionPane.showMessageDialog(null, " Data Sudah Ada!!!");
       }else{
    
                   
        String sql = "update furnitur set nama= '" + us.getNama() +"', jenis='" + us.getJenis() + "', bahan='" + us.getBahan() + "',jumlah '" + us.getJumlah() + "', harga='" + us.getHarga() + "' where id='" + id + "'";
        java.sql.Connection conn = (java.sql.Connection)app.pegawai.Database.koneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
          refresh();
                    }
            }catch (SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);
                    }
       
               }        
   
       }    
    }//GEN-LAST:event_btntamActionPerformed

    private void dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataMouseClicked
try{
        int row = data.getSelectedRow();
        String table_klik = (data.getModel().getValueAt(row, 0).toString());
          java.sql.Connection conn = (java.sql.Connection)app.pegawai.Database.koneksiDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("Select * from furnitur where id = '"+table_klik+"'");
     if(sql.next()){

         id = sql.getString("id");
         
         String nama = sql.getString("nama");
         txtnama.setText(nama);
         String bahan = sql.getString("bahan");
         cmbbah.setSelectedItem(bahan);
         String jenis = sql.getString("jenis");
         cmbjen.setSelectedItem(jenis);
         String jumlah = sql.getString("jumlah");
         txtjum.setText(jumlah);
         String harga = sql.getString("harga");
         txthar.setText(harga);
     }
     }catch (Exception e){}
      btnin.setEnabled(false);
      btntam.setEnabled(false);
      btnref.setEnabled(true);
      btnedt.setEnabled(true);
      btnhap.setEnabled(true);          // TODO add your handling code here:
    }//GEN-LAST:event_dataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void ScreenFurn() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFurniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFurniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFurniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFurniture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
    UIManager.setLookAndFeel( new FlatDarkLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFurniture().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedt;
    private javax.swing.JButton btnhap;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnkel;
    private javax.swing.JButton btnref;
    private javax.swing.JButton btntam;
    private javax.swing.JComboBox<String> cmbbah;
    private javax.swing.JComboBox<String> cmbjen;
    private javax.swing.JTable data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txthar;
    private javax.swing.JTextField txtjum;
    private javax.swing.JTextField txtnama;
    // End of variables declaration//GEN-END:variables
}
